### ISSUE TITLE
stage III

### ISSUE THREAD

**Issue by rusdevops** [Aksiniya/2k-3s-aya-hw03#1]
-  [x] 1. Можно оптимизировать
https://github.com/Aksiniya/2k-3s-aya-hw03/blob/ba3c2b4092261fd3799a3d7d8ca01a3b47f77493/include/Stack.h#L26-L27
- [x] 2. Тип возвращаемого значения должен быть `void`
https://github.com/Aksiniya/2k-3s-aya-hw03/blob/ba3c2b4092261fd3799a3d7d8ca01a3b47f77493/include/Stack.h#L63
-  [x] 3. Отсутсвует проверка `this==&s`
https://github.com/Aksiniya/2k-3s-aya-hw03/blob/ba3c2b4092261fd3799a3d7d8ca01a3b47f77493/include/Stack.h#L84
и
https://github.com/Aksiniya/2k-3s-aya-hw03/blob/ba3c2b4092261fd3799a3d7d8ca01a3b47f77493/include/Stack.h#L95
- [x] 4. Дублирование кода
https://github.com/Aksiniya/2k-3s-aya-hw03/blob/ba3c2b4092261fd3799a3d7d8ca01a3b47f77493/include/Stack.h#L84-L91
и
https://github.com/Aksiniya/2k-3s-aya-hw03/blob/ba3c2b4092261fd3799a3d7d8ca01a3b47f77493/include/Stack.h#L95-L102

**Comment by Aksiniya** [comment]
Не знаю как исправить дублирование кода в 4 пункте.

**Comment by rusdevops** [comment]
https://gist.github.com/rusdevops/f9a1b3511cd9f6924186dd272285da5b#file-pointer-cpp
